simplified some scripts

diff --git a/flashP b/flashP
--- a/flashP
+++ b/flashP
@@ -9,26 +9,21 @@
 . ./functions
 
 DISK=${4}
-PREPEND_PATH="/Devel/NOVAsom_SDK"
 
-DTB_FILESDL="${PREPEND_PATH}/DtbUserWorkArea/${5}"
-DTB_FILEQ="${PREPEND_PATH}/DtbUserWorkArea/${6}"
-KERNEL="${PREPEND_PATH}/Deploy/zImage"
-FILESYSTEM="${PREPEND_PATH}/Deploy/uInitrd"
-SPL_FILE="${PREPEND_PATH}/Deploy/SPL"
-UBOOT_IMG="${PREPEND_PATH}/Deploy/u-boot.img"
+SPL_FILE= "/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/SPL"
+UBOOT_IMG="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/u-boot.img"
+KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.15_1.2.0_ga/arch/arm/boot/zImage"
+DTB_FILESDL="/Devel/NOVAsom_SDK/DtbUserWorkArea/${5}"
+DTB_FILEQ="/Devel/NOVAsom_SDK/DtbUserWorkArea/${6}"
+FILESYSTEM="/Devel/NOVAsom_SDK/Deploy/uInitrd"
 
 echo "1" > /tmp/result
-CHECKFILES="${UBOOT_IMG} ${KERNEL} ${FILESYSTEM} ${DTB_FILEQ} ${DTB_FILESDL}"
-for i in ${CHECKFILES}; do
-	if ! [ -f $i ]; then
-		echo "Error : file ${i} does not exists!"
-		return 1
-	fi
-done
 
-[ ! -b ${DISK} ] && echo "${DISK} not found"
-[ ! -b ${DISK} ] && return 1
+if [ ! -b ${DISK} ]; then
+       echo "${DISK} not found"
+       exit
+fi
+
 sudo umount ${DISK}* >/dev/null 2>&1
 echo "Writing ${5} uSD"
 sleep 1
@@ -41,31 +36,30 @@ echo "Done"
 format_usd ${1} ${2} ${3} ${DISK}
 if [ "$?" = "1" ]; then
 	echo "Error formatting uSD!"
-	return 1
+	exit
 fi
 
 rm -rf tmpmount
 mkdir tmpmount
 sleep 1
 sudo mount ${DISK}1 tmpmount
-[ "$?" != "0" ] && return 1
-sudo rm -rf tmpmount/*
-[ "$?" != "0" ] && return 1
+[ "$?" != "0" ] && exit
 
-FILES="${UBOOT_IMG} ${KERNEL} ${FILESYSTEM}"
-echo -n "Copying "
-for i in ${FILES}; do
-	FILENAME=`basename $i`
-	echo -n "${FILENAME} "
-	sudo cp $i tmpmount/.
-	if [ "$?" != "0" ] ; then
-		echo "Error writing files!"
-		sudo umount tmpmount
-		return 1
-	fi
-done
+echo -n "Copying `basename ${UBOOT_IMG}` ..."
+sudo cp ${UBOOT_IMG} tmpmount/.
+[ "$?" != "0" ] && exit
+echo "Done"
+echo -n "Copying `basename ${KERNEL}` ..."
+sudo cp ${KERNEL} tmpmount/.
+[ "$?" != "0" ] && exit
+echo "Done"
+echo -n "Copying `basename ${UINITRD}` ..."
+sudo cp ${UINITRD} tmpmount/.
+[ "$?" != "0" ] && exit
+
+echo -n "Copying `basename ${DTB_FILEQ}` ..."
 sudo cp ${DTB_FILEQ} tmpmount/imx6q-novasomP.dtb
-echo -n "`basename ${DTB_FILEQ}` "
+echo -n "Copying `basename ${DTB_FILESDL}` ..."
 sudo cp ${DTB_FILESDL} tmpmount/imx6sdl-novasomP.dtb
 echo -n "`basename ${DTB_FILESDL}` "
 echo "Done"
@@ -75,4 +69,3 @@ sync
 
 echo "0" > /tmp/result
 echo "Write finished succesfully"
-return 0
diff --git a/flashU b/flashU
--- a/flashU
+++ b/flashU
@@ -3,21 +3,23 @@
 # ${2} is size of first user partition, if enabled
 # ${3} is size of second user partition, if enabled
 # ${4} is the device
-#DISK="/dev/sdb"
-#[ "${1}" = "" ] && ${1}="-"
-#[ "${2}" = "" ] && ${2}="16"
-#[ "${3}" = "" ] && ${3}="16"
-#[ "${4}" = "" ] && ${4}="/dev/sdb"
+# ${5} is the dtb
 # ./Uflash - 0 0 /dev/sdb"
+
+KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.43/arch/arm/boot/zImage"
+BOOTLOADER="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomU-2016.03"
+UINITRD="/Devel/NOVAsom_SDK/Deploy/uInitrd"
+UBOOT_IMX="${BOOTLOADER}/NOVAsomU/u-boot.imx"
 DISK=${4}
+DTB="${5}"
 
-KERNEL="linux-imx_4.1.43"
-BOOTLOADER="u-boot-novasom-2016.03"
-cd /Devel/NOVAsom_SDK/Bootloader/${BOOTLOADER}
+echo "1" > /tmp/result
 
-UBOOT_IMX="NOVAsomU/u-boot.imx"
-[ ! -b ${DISK} ] && echo "${DISK} not found"
-[ ! -b ${DISK} ] && return 1
+
+if [ ! -b ${DISK} ]; then
+	echo "${DISK} not found"
+	exit
+fi
 sudo umount ${DISK}* >/dev/null 2>&1
 echo "Writing NOVAsomU uSD"
 sleep 1
@@ -26,145 +28,49 @@ sudo dd if=/dev/zero of=${DISK} bs=4M count=1; sync
 sudo dd if=${UBOOT_IMX} of=${DISK} bs=512 seek=2; sync
 sync
 
+format_usd ${1} ${2} ${3} ${DISK}
 
-if [ "${1}" = "-" ]; then
-	sudo fdisk ${DISK} << __EOF__
-d
-1
-d
-2
-d
-3
-d
-4
-n
-p
-1
-
-+192M
-t
-b
-n
-p
-3
-
-+16M
-t
-3
-83
-w
-__EOF__
-
-fi
-if [ "${1}" = "1" ]; then
-	sudo fdisk ${DISK} << __EOF__
-n
-p
-1
-
-+192M
-t
-b
-n
-p
-3
-
-+16M
-t
-3
-83
-n
-p
-3
-
-+${2}M
-t
-3
-83
-w
-__EOF__
-
-fi
-
-if [ "${1}" = "2" ]; then
-	sudo fdisk ${DISK} << __EOF__
-n
-p
-1
-
-+192M
-t
-b
-n
-p
-2
-
-+16M
-t
-2
-83
-n
-p
-3
-
-+${2}M
-t
-3
-83
-
-n
-p
-
-+${3}M
-t
-4
-83
-w
-__EOF__
-
-fi
-sync
 sleep 1
 echo y | sudo mkfs.vfat -F 16 ${DISK}1 -n BOOT 
 RET=$?
 echo "mkfs.vfat returned $RET"
 if ! [ "$?" = "0" ]; then
 	echo "mkfs.vfat with error $RET"
-	return 1
+	exit
 fi
 
-echo y | sudo mkfs.ext3 -t ext3 -L P6Config ${DISK}3
+echo y | sudo mkfs.ext3 -t ext3 -L U6Config ${DISK}3
 RET=$?
 echo "mkfs.ext3 returned $RET"
 if ! [ "$?" = "0" ]; then
 	echo "mkfs.ext3 with error $RET"
-	return 1
+	exit
 fi
 
 if [ "${1}" = "1" ]; then
-	echo y | sudo sudo mkfs.ext3 -t ext3 -L P6user1 ${DISK}2
+	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}2
 	RET=$?
 	echo "mkfs.ext3 returned $RET"
 	if ! [ "$?" = "0" ]; then
 		echo "mkfs.ext3 with error $RET"
-		return 1
+		exit
 	fi
 fi
 
 if [ "${1}" = "2" ]; then
-	echo y | sudo sudo mkfs.ext3 -t ext3 -L P6user1 ${DISK}4
+	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}4
 	RET=$?
 	echo "mkfs.ext3 returned $RET"
 	if ! [ "$?" = "0" ]; then
 		echo "mkfs.ext3 with error $RET"
-		return 1
+		exit
 	fi
-	echo y | sudo mkfs.ext3 -t ext3 -L P6user2 ${DISK}4
+	echo y | sudo mkfs.ext3 -t ext3 -L U6user2 ${DISK}4
 	RET=$?
 	echo "mkfs.ext3 returned $RET"
 	if ! [ "$?" = "0" ]; then
 		echo "mkfs.ext3 with error $RET"
-		return 1
+		exit
 	fi
 fi
 
@@ -174,31 +80,31 @@ rm -rf tmpmount
 mkdir tmpmount
 sleep 1
 sudo mount ${DISK}1 tmpmount
-[ "$?" != "0" ] && return 1
+[ "$?" != "0" ] && exit
 sudo rm -rf tmpmount/*
-[ "$?" != "0" ] && return 1
+[ "$?" != "0" ] && exit
 echo `pwd`
 echo -n "Copying novasomu.dtb ..."
-sudo cp ../../Deploy/novasomu.dtb tmpmount/.
-[ "$?" != "0" ] && return 1
+sudo cp ${DTB} tmpmount/novasomu.dtb
+[ "$?" != "0" ] && exit
 echo "Done"
 echo -n "Copying u-boot files ..."
-sudo cp ../../Bootloader/${BOOTLOADER}/NOVAsomU/u-boot.imx tmpmount/.
-[ "$?" != "0" ] && return 1
+sudo cp ${UBOOT_IMX} tmpmount/.
+[ "$?" != "0" ] && exit
 echo "Done"
 echo -n "Copying zImage ..."
-sudo cp ../../Kernel/${KERNEL}/arch/arm/boot/zImage tmpmount/.
-[ "$?" != "0" ] && return 1
+sudo cp ${KERNEL} tmpmount/.
+[ "$?" != "0" ] && exit
 echo "Done"
 echo -n "Copying uInitrd ..."
-sudo cp ../../Deploy/uInitrd tmpmount/.
-[ "$?" != "0" ] && return 1
+sudo cp ${UINITRD} tmpmount/.
+[ "$?" != "0" ] && exit
 echo "Done"
-sudo cp ../../Bootloader/${BOOTLOADER}/ddr-test-uboot-jtag-mx6ull.bin tmpmount/.
-sudo cp ../../Bootloader/${BOOTLOADER}/qspi-header.bin tmpmount/qspi-header.bin
+#sudo cp ../../Bootloader/${BOOTLOADER}/ddr-test-uboot-jtag-mx6ull.bin tmpmount/.
+#sudo cp ../../Bootloader/${BOOTLOADER}/qspi-header.bin tmpmount/qspi-header.bin
 sudo umount tmpmount
 sync
 sudo umount ${DISK}
 sync
 
-return 0
+echo "0" > /tmp/result
