Fixed parameters

diff --git a/flashP b/flashP
--- a/flashP
+++ b/flashP
@@ -5,24 +5,39 @@
 # ${4} is the device
 # ${5} is the dtb for solo/dl
 # ${6} is the dtb for quad
+# ${7} is the NOVAsomParams file
+# ${8} is the ramdisk size
 
 . ./functions
 
 DISK=${4}
 
-SPL_FILE= "/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/SPL"
+SPL_FILE="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/SPL"
 UBOOT_IMG="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/u-boot.img"
 KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.15_1.2.0_ga/arch/arm/boot/zImage"
 DTB_FILESDL="/Devel/NOVAsom_SDK/DtbUserWorkArea/${5}"
 DTB_FILEQ="/Devel/NOVAsom_SDK/DtbUserWorkArea/${6}"
-FILESYSTEM="/Devel/NOVAsom_SDK/Deploy/uInitrd"
+UINITRD="/Devel/NOVAsom_SDK/Deploy/uInitrd"
+NOVASOMPARAMS="/Devel/NOVAsom_SDK/Utils/BootParameters/$7"
+RAMDISK_SIZE="$8"
+
 
 echo "1" > /tmp/result
+
+FILES="$SPL_FILE $UBOOT_IMG $KERNEL $DTB_FILESDL $DTB_FILEQ $UINITRD $NOVASOMPARAMS"
+for i in ${FILES}; do
+	if ! [ -f ${i} ]; then
+		echo "File ${i} not found"
+		exit
+	fi
+done
 
 if [ ! -b ${DISK} ]; then
        echo "${DISK} not found"
        exit
 fi
+
+echo "Everything is ok, proceeding"
 
 sudo umount ${DISK}* >/dev/null 2>&1
 echo "Writing ${5} uSD"
@@ -56,6 +71,11 @@ echo "Done"
 echo -n "Copying `basename ${UINITRD}` ..."
 sudo cp ${UINITRD} tmpmount/.
 [ "$?" != "0" ] && exit
+echo -n "Copying `basename ${NOVASOMPARAMS}` ..."
+echo "setramsize=setenv rdsize ${RAMDISK_SIZE}" > ../Deploy/NOVAsomParams
+cat ${NOVASOMPARAMS} >> ../Deploy/NOVAsomParams
+sudo cp ../Deploy/NOVAsomParams tmpmount/NOVAsomParams
+[ "$?" != "0" ] && exit
 
 echo -n "Copying `basename ${DTB_FILEQ}` ..."
 sudo cp ${DTB_FILEQ} tmpmount/imx6q-novasomP.dtb
@@ -66,6 +86,14 @@ echo "Done"
 
 sudo umount tmpmount
 sync
+cd ../Deploy
+rm -f SPL u-boot.img zImage imx6q-novasomP.dtb imx6sdl-novasomP.dtb
+ln -s $SPL_FILE
+ln -s $UBOOT_IMG
+ln -s $KERNEL
+ln -s $DTB_FILESDL imx6sdl-novasomP.dtb
+ln -s $DTB_FILEQ imx6q-novasomP.dtb
+
 
 echo "0" > /tmp/result
 echo "Write finished succesfully"
diff --git a/flashU b/flashU
--- a/flashU
+++ b/flashU
@@ -4,7 +4,11 @@
 # ${3} is size of second user partition, if enabled
 # ${4} is the device
 # ${5} is the dtb
+# ${6} is the NOVAsomParams file
+# ${7} is the ramdisk size
 # ./Uflash - 0 0 /dev/sdb"
+
+. ./functions
 
 KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.43/arch/arm/boot/zImage"
 BOOTLOADER="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomU-2016.03"
@@ -12,9 +16,17 @@ UINITRD="/Devel/NOVAsom_SDK/Deploy/uInitrd"
 UBOOT_IMX="${BOOTLOADER}/NOVAsomU/u-boot.imx"
 DISK=${4}
 DTB="${5}"
+NOVASOMPARAMS="/Devel/NOVAsom_SDK/Utils/BootParameters/$6"
+RAMDISK_SIZE="$7"
 
 echo "1" > /tmp/result
-
+FILES="$BOOTLOADER $KERNEL $DTB $UINITRD $NOVASOMPARAMS"
+for i in ${FILES}; do
+        if ! [ -f ${i} ]; then
+                echo "File ${i} not found"
+                exit
+        fi
+done
 
 if [ ! -b ${DISK} ]; then
 	echo "${DISK} not found"
@@ -100,6 +112,13 @@ echo -n "Copying uInitrd ..."
 sudo cp ${UINITRD} tmpmount/.
 [ "$?" != "0" ] && exit
 echo "Done"
+echo -n "Copying `basename ${NOVASOMPARAMS}` ..."
+echo "setramsize=setenv rdsize ${RAMDISK_SIZE}" > ../Deploy/NOVAsomParams
+cat ${NOVASOMPARAMS} >> ../Deploy/NOVAsomParams
+sudo cp ../Deploy/NOVAsomParams tmpmount/NOVAsomParams
+[ "$?" != "0" ] && exit
+
+
 #sudo cp ../../Bootloader/${BOOTLOADER}/ddr-test-uboot-jtag-mx6ull.bin tmpmount/.
 #sudo cp ../../Bootloader/${BOOTLOADER}/qspi-header.bin tmpmount/qspi-header.bin
 sudo umount tmpmount
@@ -108,3 +127,5 @@ sudo umount ${DISK}
 sync
 
 echo "0" > /tmp/result
+echo "Write finished succesfully"
+
